version: "3.9"
services:
  neo4j:
    image: neo4j:5.22
    container_name: aurorarag-neo4j
    restart: unless-stopped
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_security_procedures_unrestricted=gds.*
      - NEO4J_PLUGINS=["graph-data-science"]
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
    volumes:
      - neo4j_data:/data
      - neo4j_plugins:/plugins
      - neo4j_import:/import
volumes:
  neo4j_data:
  neo4j_plugins:
  neo4j_import:
